server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;
    url: jdbc:h2:mem:demodb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console: 
      enabled: true
      path: /h2-console
  
  jpa: 
    hibernate: 
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
logging:  
  pattern:    
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"  
  level:
    root: info
    com.namanok: debug
      
jwt:
  secret-key: mysecret!