server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  h2:
    console:
      enable: true
      
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  
